### ISSUE TITLE
фикс бд

### ISSUE THREAD

**Issue by Evgencheg** [Lost-Paradise-Project/Lost-Paradise#182]
### Описание

аы

### Шаги воспроизведения

аы

### Скриншоты

аы

**Comment by Evgencheg** [comment]
2024-09-22T17:20:22.6626746+03:00 [ERRO] db.ef: Failed executing DbCommand (9ms) [Parameters=[@p0='?' (DbType = Int32), @p1='?' (DbType = Int32), @p2='?' (DbType = Int32), @p3='?' (DbType = Int32), @p4='?' (DbType = Int32), @p5='?' (DbType = Int32), @p6='?' (DbType = Int32), @p7='?' (DbType = Int32), @p8='?' (DbType = Int32), @p9='?' (DbType = Int32), @p10='?' (DbType = Int32), @p12='?' (DbType = Int32), @p11='?' (DbType = Object), @p13='?' (DbType = Int32), @p14='?' (DbType = Int32), @p15='?' (DbType = Int32), @p16='?' (DbType = Int32), @p17='?' (DbType = Int32), @p18='?' (DbType = Int32), @p19='?', @p20='?' (DbType = Int32), @p21='?', @p22='?' (DbType = Int32), @p23='?', @p24='?' (DbType = Int32), @p25='?', @p26='?' (DbType = Int32), @p27='?' (DbType = Int32), @p28='?', @p29='?' (DbType = Int32), @p30='?' (DbType = Int32), @p31='?', @p32='?' (DbType = Int32), @p33='?' (DbType = Int32), @p34='?', @p35='?' (DbType = Int32), @p36='?' (DbType = Int32), @p37='?', @p38='?' (DbType = Int32), @p39='?' (DbType = Int32), @p40='?', @p41='?' (DbType = Int32), @p42='?' (DbType = Int32), @p43='?', @p44='?' (DbType = Int32), @p45='?' (DbType = Int32), @p46='?', @p47='?' (DbType = Int32), @p48='?' (DbType = Int32), @p49='?', @p50='?' (DbType = Int32), @p51='?', @p52='?' (DbType = Int32), @p53='?', @p54='?' (DbType = Int32), @p55='?' (DbType = Int32), @p56='?', @p57='?' (DbType = Int32), @p58='?', @p59='?' (DbType = Int32), @p60='?'], CommandType='Text', CommandTimeout='30']
DELETE FROM antag
WHERE antag_id = @p0;
DELETE FROM antag
WHERE antag_id = @p1;
DELETE FROM job
WHERE job_id = @p2;
DELETE FROM job
WHERE job_id = @p3;
DELETE FROM job
WHERE job_id = @p4;
DELETE FROM job
WHERE job_id = @p5;
DELETE FROM job
WHERE job_id = @p6;
DELETE FROM job
WHERE job_id = @p7;
DELETE FROM job
WHERE job_id = @p8;
DELETE FROM loadout
WHERE loadout_id = @p9;
DELETE FROM loadout
WHERE loadout_id = @p10;
UPDATE profile SET markings = @p11
WHERE profile_id = @p12;
DELETE FROM trait
WHERE trait_id = @p13;
DELETE FROM trait
WHERE trait_id = @p14;
DELETE FROM antag
WHERE antag_id = @p15;
DELETE FROM job
WHERE job_id = @p16;
DELETE FROM loadout
WHERE loadout_id = @p17;
DELETE FROM trait
WHERE trait_id = @p18;
INSERT INTO antag (antag_name, profile_id)
VALUES (@p19, @p20)
RETURNING antag_id;
INSERT INTO antag (antag_name, profile_id)
VALUES (@p21, @p22)
RETURNING antag_id;
INSERT INTO antag (antag_name, profile_id)
VALUES (@p23, @p24)
RETURNING antag_id;
INSERT INTO job (job_name, priority, profile_id)
VALUES (@p25, @p26, @p27)
RETURNING job_id;
INSERT INTO job (job_name, priority, profile_id)
VALUES (@p28, @p29, @p30)
RETURNING job_id;
INSERT INTO job (job_name, priority, profile_id)
VALUES (@p31, @p32, @p33)
RETURNING job_id;
INSERT INTO job (job_name, priority, profile_id)
VALUES (@p34, @p35, @p36)
RETURNING job_id;
INSERT INTO job (job_name, priority, profile_id)
VALUES (@p37, @p38, @p39)
RETURNING job_id;
INSERT INTO job (job_name, priority, profile_id)
VALUES (@p40, @p41, @p42)
RETURNING job_id;
INSERT INTO job (job_name, priority, profile_id)
VALUES (@p43, @p44, @p45)
RETURNING job_id;
INSERT INTO job (job_name, priority, profile_id)
VALUES (@p46, @p47, @p48)
RETURNING job_id;
INSERT INTO loadout (loadout_name, profile_id)
VALUES (@p49, @p50)
RETURNING loadout_id;
INSERT INTO loadout (loadout_name, profile_id)
VALUES (@p51, @p52)
RETURNING loadout_id;
INSERT INTO loadout (loadout_name, profile_id)
VALUES (@p53, @p54)
RETURNING loadout_id;
INSERT INTO trait (profile_id, trait_name)
VALUES (@p55, @p56)
RETURNING trait_id;
INSERT INTO trait (profile_id, trait_name)
VALUES (@p57, @p58)
RETURNING trait_id;
INSERT INTO trait (profile_id, trait_name)
VALUES (@p59, @p60)
RETURNING trait_id;
2024-09-22T17:20:22.6862265+03:00 [ERRO] db.ef: An exception occurred in the database while saving changes for context type 'Content.Server.Database.PostgresServerDbContext'.
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while saving the entity changes. See the inner exception for details.
 ---> Npgsql.PostgresException (0x80004005): 23505: duplicate key value violates unique constraint "IX_antag_profile_id_antag_name"

DETAIL: Detail redacted as it may contain sensitive data. Specify 'Include Error Detail' in the connection string to include this information.
   at Npgsql.Internal.NpgsqlConnector.ReadMessageLong(Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(Boolean async, CommandBehavior behavior, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(Boolean async, CommandBehavior behavior, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
  Exception data:
    Severity: ERROR
    SqlState: 23505
    MessageText: duplicate key value violates unique constraint "IX_antag_profile_id_antag_name"
    Detail: Detail redacted as it may contain sensitive data. Specify 'Include Error Detail' in the connection string to include this information.
    SchemaName: public
    TableName: antag
    ConstraintName: IX_antag_profile_id_antag_name
    File: nbtinsert.c
    Line: 663
    Routine: _bt_check_unique
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(StateManager stateManager, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.NpgsqlExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
2024-09-22T17:20:22.9115230+03:00 [ERRO] runtime: Caught exception in "Async Queued Callback"
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while saving the entity changes. See the inner exception for details.
 ---> Npgsql.PostgresException (0x80004005): 23505: duplicate key value violates unique constraint "IX_antag_profile_id_antag_name"

DETAIL: Detail redacted as it may contain sensitive data. Specify 'Include Error Detail' in the connection string to include this information.
   at Npgsql.Internal.NpgsqlConnector.ReadMessageLong(Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(Boolean async, CommandBehavior behavior, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(Boolean async, CommandBehavior behavior, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
  Exception data:
    Severity: ERROR
    SqlState: 23505
    MessageText: duplicate key value violates unique constraint "IX_antag_profile_id_antag_name"
    Detail: Detail redacted as it may contain sensitive data. Specify 'Include Error Detail' in the connection string to include this information.
    SchemaName: public
    TableName: antag
    ConstraintName: IX_antag_profile_id_antag_name
    File: nbtinsert.c
    Line: 663
    Routine: _bt_check_unique
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(StateManager stateManager, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.NpgsqlExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Content.Server.Database.ServerDbBase.SaveCharacterSlotAsync(NetUserId userId, ICharacterProfile profile, Int32 slot) in /home/runner/work/Lost-Paradise/Lost-Paradise/Content.Server/Database/ServerDbBase.cs:line 113
   at Content.Server.Database.ServerDbBase.SaveCharacterSlotAsync(NetUserId userId, ICharacterProfile profile, Int32 slot) in /home/runner/work/Lost-Paradise/Lost-Paradise/Content.Server/Database/ServerDbBase.cs:line 113
   at Content.Server.Database.ServerDbManager.RunDbCommand(Func`1 command) in /home/runner/work/Lost-Paradise/Lost-Paradise/Content.Server/Database/ServerDbManager.cs:line 899
   at Content.Server.Preferences.Managers.ServerPreferencesManager.SetProfile(NetUserId userId, Int32 slot, ICharacterProfile profile) in /home/runner/work/Lost-Paradise/Lost-Paradise/Content.Server/Preferences/Managers/ServerPreferencesManager.cs:line 140
   at Content.Server.Preferences.Managers.ServerPreferencesManager.HandleUpdateCharacterMessage(MsgUpdateCharacter message) in /home/runner/work/Lost-Paradise/Lost-Paradise/Content.Server/Preferences/Managers/ServerPreferencesManager.cs:line 99
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Robust.Shared.Asynchronous.RobustSynchronizationContext.ProcessPendingTasks() in /home/runner/work/Lost-Paradise/Lost-Paradise/RobustToolbox/Robust.Shared/Asynchronous/RobustSynchronizationContext.cs:line 54

**Comment by Evgencheg** [comment]
[message(1).txt](https://github.com/user-attachments/files/17090364/message.1.txt)
